package:
    name: hfm
    version: 0.2.1

source:
    git_url: https://github.com/Mirebeau/HamiltonFastMarching

build:
    number: 1000
    string: py{{ environ.get('PYTHON_VERSION', 'unk') }}

requirements:
    build:
        #- {{ compiler('cxx') }}
        - python {{PY_VER}}*
        - cmake
    host:
        - setuptools
        - pybind11
        - numpy
    run:
        - pybind11
        - numpy

test:
    imports:
        HFMpy.HFM_Isotropic2

about:
    dev_url: https://github.com/Mirebeau/HamiltonFastMarching
    license: Licence GPU GPL v3
    license_family: GPL

extra:
    recipe-maintainers:
        - gouarin
        - hleclerc
        
