name: build conda
on: [push]
jobs:
  build_conda:
    name: build conda (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"] # 
        python-version: ["3.7", "3.8", "3.9"] # 
    steps:
      - uses: actions/checkout@v2
      - uses: rlalik/setup-cpp-compiler@v1
        with:
          compiler: latest
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yaml
          auto-activate-base: false
          auto-update-conda: true
      - name: Conda build
        shell: bash -l {0}
        env:
          ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
          ANACONDA_LOGIN: ${{ secrets.ANACONDA_LOGIN }}
        run: |
          conda build . --output-folder dist/conda-${{ matrix.python-version }} --python=${{ matrix.python-version }} -c AGD-LBR
          OUTPUT_FILE=`find dist/conda-${{ matrix.python-version }} -name "*.tar.bz2"`
          echo Y | anaconda login --username $ANACONDA_LOGIN --password "$ANACONDA_PASSWORD"
          anaconda upload --force --user agd-lbr "$OUTPUT_FILE"

#
# conda config --set always_yes yes --set changeps1 no 
# # conda update -q conda
# #conda create -q -n test-environment-${{ matrix.python-version }} python=${{ matrix.python-version }} conda-build conda-verify anaconda-client
# conda create -q -n test-environment-${{ matrix.python-version }} python=${{ matrix.python-version }} conda-build conda-verify anaconda-client
# source activate test-environment-${{ matrix.python-version }}
# # conda info -a
# echo Y | anaconda login --username $ANACONDA_LOGIN --password "$ANACONDA_PASSWORD"
# conda build . --output-folder dist/conda-${{ matrix.python-version }} --python=${{ matrix.python-version }} -c agd-lbr
# OUTPUT_FILE=`find dist/conda-${{ matrix.python-version }} -name "*.tar.bz2"`
# anaconda upload --force --user agd-lbr "$OUTPUT_FILE"
# OUTPUT_FILE=`find dist/conda-3.9 -name "*.tar.bz2"`
